#!/usr/bin/env python3
"""
Download comprehensive English word lists for LingoDom.

Strategy:
  1. Download NLTK words corpus (proper English dictionary, ~235k words)
  2. Download word frequency data (top 50k from Wikipedia)
  3. Cross-reference: word must be in BOTH the dictionary AND frequency list
  4. Filter out: proper nouns, names, places, acronyms, abbreviations,
     obscure/archaic words, foreign words, and child-inappropriate content

Usage:
  python scripts/generate_words.py

Output:
  app/src/main/assets/words_4.txt
  app/src/main/assets/words_5.txt
  app/src/main/assets/words_6.txt
  app/src/main/assets/words_7.txt
"""

import os
import re
import json
import urllib.request

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
ASSETS_DIR = os.path.join(PROJECT_ROOT, "app", "src", "main", "assets")

# NLTK words corpus (proper English dictionary — lowercase common words only)
NLTK_URL = "https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/words.zip"

# Backup: dwyl/english-words (public domain, ~370k alpha-only words)
DWYL_URL = "https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt"

# Word frequency list (hermitdave/FrequencyWords - Wikipedia-based, top 50k)
FREQ_URL = "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/en/en_50k.txt"

# ── Child-safety blocklist ────────────────────────────────────────────
# Categories: profanity, sexual, violence, drugs/alcohol, slurs,
#             death/gore, weapons, hate, and other mature themes.
BLOCKLIST = {
    # ── Profanity / vulgar ───────────────────────────────────
    "anal", "anus", "arse", "arses", "ass", "asses",
    "bastard", "bitch", "bitchy", "bloody", "blow",
    "boob", "boobs", "booger", "boner", "boners", "bugger",
    "bullshit", "butt", "butts",
    "cock", "cocks", "crap", "craps", "crud", "cum", "cums", "cunt",
    "damn", "damns", "damned", "dammit", "dick", "dicks",
    "douche", "dung", "dyke", "dykes",
    "fag", "fags", "fart", "farts", "freak", "freaks",
    "fuck", "fucks", "fucked", "fucker",
    "gash", "git", "gits", "goddamn", "groin",
    "hell", "hells", "homo", "hump", "humps",
    "idiot", "idiots",
    "jerk", "jerks",
    "kink", "kinks", "knob", "knobs",
    "lame", "loser", "losers", "lust", "lusts",
    "moan", "moans", "moron", "morons",
    "nerd", "nerds", "nipple", "nipples", "nude", "nudes",
    "oral", "orals",
    "pansy", "pee", "pees", "penis", "perv", "pervs",
    "pimp", "pimps", "piss", "pissed",
    "poop", "poops", "porn", "porno", "prick", "pricks",
    "puke", "pukes", "pussy",
    "queer",
    "rump",
    "scum", "semen", "sexy", "shag", "shags",
    "shit", "shits", "shitty", "skank", "slag", "slags",
    "slut", "sluts", "smut", "smuts", "snot",
    "sperm", "spew", "suck", "sucks",
    "tit", "tits", "turd", "turds", "twat", "twats", "twit",
    "wank", "wanks", "wanker", "whore", "whores",

    # ── Sexual / adult content ───────────────────────────────
    "arousal", "bondage", "bordel", "boner",
    "breasts", "brothel", "climax", "coital", "coitus",
    "condom", "condoms", "dildo", "dildos",
    "erect", "erects", "erotic", "escort",
    "fetish", "fondle", "fondles", "foreplay",
    "genital", "grope", "groped", "gropes",
    "handjob", "harem", "hooker", "hookers", "horny",
    "incest", "kinky",
    "libido", "lingerie",
    "masochism", "masturbate",
    "molest", "molests",
    "naked", "naughty",
    "orgasm", "orgasms", "orgy",
    "pedophile", "phallus", "playboy",
    "pornography", "prostitute",
    "seduce", "seduces", "sensual",
    "sexual", "stripper", "syphilis",
    "taboo", "topless",
    "vagina", "vaginal", "vibrator", "virgin", "voyeur",

    # ── Violence / gore ──────────────────────────────────────
    "abuse", "abused", "abuser", "abuses",
    "assault", "assaults",
    "behead", "beheads", "bleed", "bleeds", "blood", "bloody",
    "brutal", "bruise", "bruises",
    "carnage", "corpse", "corpses", "cruelly", "cruelty",
    "decapitate", "dismember",
    "execute", "executed",
    "gory", "gore", "gouge", "gouges", "gunshot",
    "homicide",
    "impale", "impaled",
    "kill", "killed", "killer", "killers", "kills",
    "maim", "maimed", "maims", "massacre", "mutilate",
    "murder", "murders", "murdered", "murderer",
    "pummel",
    "rape", "raped", "rapes", "rapist", "rapists",
    "slain", "slay", "slaying", "slays", "slew",
    "stab", "stabbed", "stabs",
    "strangle", "suffocate",
    "terror", "terrorist", "torture", "tortured", "tortures",
    "victim", "victims", "violence", "violent",

    # ── Weapons ──────────────────────────────────────────────
    "ammo", "arsenal",
    "bomb", "bombs", "bomber", "bullet", "bullets",
    "cannon", "carbine",
    "dagger", "daggers", "dynamite",
    "explosive", "explosives",
    "firearm", "firearms",
    "grenade", "grenades", "gun", "guns", "gunfire",
    "handgun", "holster",
    "landmine",
    "machete", "missile", "missiles", "mortar",
    "pistol", "pistols",
    "revolver", "rifle", "rifles", "rocket", "rockets",
    "shotgun", "shotguns", "sniper", "snipers",
    "torpedo",
    "warhead", "weapon", "weapons",

    # ── Death / dark ─────────────────────────────────────────
    "burial", "buried",
    "casket", "cemetery", "coffin", "coffins",
    "dead", "deadly", "death", "deaths", "deathly", "decay",
    "demon", "demons", "devil", "devils",
    "die", "died", "dies", "doom", "doomed",
    "drown", "drowned", "drowns",
    "fatal", "fatally", "funeral", "funerals",
    "ghost", "ghosts", "ghastly", "ghoul", "ghouls",
    "grave", "graves",
    "haunt", "haunts", "haunted",
    "hearse",
    "lethal",
    "macabre", "morgue",
    "noose",
    "obituary",
    "perish", "perished",
    "skull", "skulls",
    "suicide",
    "tomb", "tombs", "tombstone",
    "undead",
    "zombie", "zombies",

    # ── Drugs / alcohol / smoking ────────────────────────────
    "addict", "addicts", "addicted",
    "beer", "beers", "binge", "booze", "bourbon", "brandy", "brew",
    "cannabis", "cigar", "cigars", "cocaine", "cocktail",
    "crack",
    "dope", "doping", "drug", "drugs", "drunk", "drunks",
    "ecstasy",
    "gin", "gins",
    "hashish", "heroin", "highball",
    "inject", "injected", "intoxicate",
    "junkie", "junkies",
    "keg", "kegs", "ketamine",
    "lager", "liquor", "liquors", "lsd",
    "marijuana", "martini", "mead", "meth",
    "narcotic", "narcotics", "nicotine",
    "opioid", "opioids", "opium", "overdose",
    "rum", "rums",
    "scotch", "smoke", "smoked", "smoker", "smokes", "smoking",
    "sniff", "snort", "stoned", "stoner",
    "tobacco", "tequila",
    "vodka",
    "wasted", "weed", "whiskey", "whisky", "wine", "wines",

    # ── Slurs / hate speech ──────────────────────────────────
    "bigot", "bigots", "bigotry",
    "cracker",
    "faggot", "faggots",
    "gringo",
    "halfbreed",
    "infidel", "infidels",
    "nazi", "nazis",
    "nigger", "niggers", "nigga",
    "racist", "racists", "racism",
    "redneck", "rednecks", "retard", "retards", "retarded",
    "sexism", "sexist",
    "spic", "spics",
    "supremacy", "supremacist",
    "thug", "thugs",
    "trash",
    "xenophobe",

    # ── Gambling ─────────────────────────────────────────────
    "bet", "bets", "betting",
    "casino", "casinos",
    "gamble", "gambles", "gambler", "gambling",
    "jackpot", "jackpots",
    "poker",
    "roulette",
    "slots", "wager", "wagers",

    # ── Other inappropriate / scary for children ─────────────
    "abduct", "abducts",
    "adultery",
    "asylum",
    "autopsy",
    "cannibal", "cannibals",
    "captive", "captives",
    "corrupt", "corrupts",
    "creep", "creepy",
    "cult", "cults",
    "curse", "curses", "cursed",
    "despair",
    "disease", "diseased",
    "evil", "evils",
    "fear", "fears",
    "fiend", "fiends",
    "flesh",
    "foe", "foes",
    "gang", "gangs", "gangster",
    "grim",
    "hate", "hated", "hater", "haters", "hates", "hatred",
    "hex",
    "hostage", "hostages",
    "insane", "insanity",
    "kidnap", "kidnaps", "kidnapped",
    "lunatic", "lunatics",
    "madman", "madness",
    "menace", "menaces",
    "misery",
    "monster", "monsters",
    "nightmare", "nightmares",
    "occult",
    "outlaw", "outlaws",
    "panic", "panics",
    "plague", "plagues",
    "poison", "poisons", "poisoned",
    "predator", "predators",
    "prison", "prisons", "prisoner",
    "psycho", "psychos",
    "ransom", "ransoms",
    "revenge",
    "satan", "satanic",
    "savage", "savages",
    "scare", "scared", "scares", "scary",
    "scream", "screams",
    "sinful", "sinister",
    "slavery", "slaves",
    "sorcery",
    "spawn", "spawns",
    "spooky",
    "stalker", "stalkers",
    "steal", "steals", "stolen",
    "threat", "threats",
    "thief", "thieves",
    "toxic",
    "trauma", "traumas",
    "tyrant", "tyrants",
    "venom", "venoms",
    "vile",
    "villain", "villains",
    "wicked",
    "witch", "witches",
    "wound", "wounds", "wounded",
    "wrath",
}

# ── Names, places, acronyms, and other non-dictionary words ──────────
# These appear in frequency data because Wikipedia mentions them often,
# but they are NOT regular English vocabulary words.
# This list is intentionally large to catch as many as possible.
NAMES_AND_ACRONYMS = {
    # ── 4-letter names ───────────────────────────────────────
    "aaru", "abba", "abby", "abel", "aclu", "adam", "addy", "aden", "agha",
    "agos", "agra", "agua", "ahab", "aint", "ajax", "alai", "alan", "alba", "alec", "alex",
    "algy", "alia", "alle", "allo", "alls", "alma", "alps", "amal", "amar", "amex", "amin",
    "amir", "amis", "amit", "amma", "ammu", "ambo", "amor", "amos", "anda", "andi",
    "ands", "andy", "anil", "anna", "anne", "anni", "aqua", "arab", "aren", "ares",
    "argo", "arne", "arvo", "arya", "asha", "asia", "asap", "atta", "auld", "awol", "asta", "baal", "baba",
    "babi", "babs", "babu", "bach", "baht", "bain", "baja", "baku", "bala",
    "bali", "balu", "bana", "bara", "bari", "barr", "bart", "baze", "beal",
    "beau", "beck", "bein", "bela", "bene", "beni", "berk", "bern", "bert",
    "bess", "beth", "bibi", "bien", "biff", "bing", "bink", "birk",
    "bish", "boba", "bobo", "boca", "bock", "boer", "bogo", "bois",
    "boko", "bolo", "bona", "bono", "bora", "borg", "bose", "boyd",
    "boyo", "bozo", "brad", "bram", "bree", "bren", "bret", "brit",
    "brrr", "buda", "burk", "burt", "buts", "caca", "cade", "cady", "cain",
    "cana", "cann", "capa", "capo", "cara", "carl", "caro", "carr",
    "cary", "casa", "cass", "cate", "cath", "cava", "cern", "cert",
    "chad", "chai", "cham", "chan", "chao", "chee", "chen", "cher",
    "chet", "chez", "chem", "chil", "chol", "chon", "chou", "choy", "chun",
    "clem", "clio", "clit", "cmdr", "cobb", "coca", "coed", "coli",
    "cong", "conn", "coon", "copa", "cora", "cort", "cory", "cree", "cris",
    "cuba", "czar", "dada", "dade", "dado", "dago", "dale", "dali",
    "dana", "dane", "dani", "dato", "dave", "davy", "deke", "deli",
    "dell", "demi", "dere", "desi", "deus", "deux", "deva", "devi",
    "dian", "dias", "dich", "didn", "dido", "diem", "dike", "dino",
    "dion", "dirk", "dodd", "dodo", "doge", "dojo", "dona", "dong",
    "dont", "doon", "dora", "dori", "dorn", "dory", "dosa", "doss",
    "dost", "doth", "doug", "dowd", "duan", "duce", "duma", "dumb",
    "eben", "eden", "edna", "egad", "elia", "ella", "elle", "elon",
    "elsa", "emil", "emir", "emma", "emmy", "enid", "enos", "erin",
    "eric", "erie", "erik", "eros", "eton", "etta", "evan", "eyre",
    "ezra", "fado", "fain", "falk", "fane", "faro", "faun", "feck", "fess",
    "feta", "fide", "fido", "fiji", "fini", "fink", "finn", "fisk",
    "fitz", "flor", "foss", "frag", "frat", "frau", "fred", "frey",
    "frig", "fuji", "gabe", "gabi", "gaby", "gael", "gaga", "gage",
    "gaia", "gail", "galt", "gant", "garb", "gare", "gary", "gaul",
    "geet", "geez", "geir", "gena", "gene", "gere", "geta", "geum",
    "ghee", "gigi", "gila", "giro", "gobi", "goff", "gogo", "goli",
    "gona", "gook", "goop", "gora", "goss", "goth", "goto", "graf",
    "gras", "greg", "grog", "guam", "guan", "gugu", "guna", "gung", "gwen",
    "gyro", "haji", "hajj", "hank", "hans", "harv", "hasn", "hast",
    "hasn", "hast",
    "hath", "heer", "hehe", "heil", "hein", "hemp", "heng", "hera",
    "herb", "herr", "hick", "hing", "hiro", "hogg", "hoke", "hola",
    "holi", "holl", "holm", "holt", "hopi", "hora", "hors", "hoss",
    "howe", "hows", "huck", "huer", "huey", "hugh", "hugo", "hume", "hunh",
    "huns", "hwan", "hyde", "hypo", "iago", "ibis", "ilya", "imam",
    "iman", "inca", "indy", "inez", "inga", "iowa", "iran", "iraq",
    "iris", "irma", "isis", "isnt", "ivan", "izzy", "jain", "jake", "jami",
    "jane", "jarl", "java", "jean", "jefe", "jeff", "jeon", "jess",
    "jesu", "jiao", "jiff", "jill", "jing", "jinn", "jive", "joan",
    "jobe", "jock", "joel", "joey", "john", "joie", "jong", "joni",
    "joon", "jose", "josh", "joss", "jour", "jove", "juan", "jude",
    "judo", "judy", "juha", "juju", "juke", "jule", "juno", "jura",
    "juri", "kaka", "kala", "kali", "kama", "kami", "kana", "kane",
    "kang", "kant", "kapa", "kari", "karl", "kate", "kath", "katy",
    "kayo", "keck", "kees", "kell", "kemp", "keno", "kens", "kent",
    "khan", "kiev", "kike", "kiki", "kiku", "kino", "kirk", "klan",
    "knox", "knut", "koch", "koda", "kohl", "koko", "kong", "kook",
    "kora", "kota", "koto", "kris", "kuan", "kuba", "kudo", "kuei",
    "kuki", "kuku", "kung", "kurt", "kwan", "kyle", "lait", "lakh",
    "lalo", "lama", "lana", "lang", "laos", "lars", "lata", "leah",
    "lech", "leda", "leif", "lena", "lene", "leng", "leno", "leon",
    "leto", "levi", "lida", "lido", "lila", "lill", "lily", "lima",
    "lina", "lind", "linn", "lino", "lira", "lire", "lisa", "lise",
    "liza", "lobo", "loca", "lois", "loki", "lola", "lolo", "lora",
    "lori", "loup", "lowe", "luce", "lucy", "ludo", "luis", "luke",
    "lula", "lulu", "luna", "lupe", "lynn", "lyon", "lyra", "maam",
    "maar", "mack", "madi", "mado", "mads", "maga", "mage", "magi",
    "maha", "mahi", "maia", "maja", "maki", "mako", "mala", "mali",
    "malo", "mama", "mamo", "mana", "mang", "mani", "mann", "mano",
    "mara", "marc", "marg", "mari", "mark", "mars", "mart", "maru", "marx",
    "mary", "masa", "matt", "maud", "maya", "mayo", "meer", "mein", "meng", "merc",
    "merv", "mesa", "mets", "miao", "mick", "migs", "mike", "miki",
    "mila", "milo", "milt", "mima", "mimi", "mina", "ming", "mino",
    "mira", "miri", "miro", "miso", "mmmm", "modi", "mogo", "mojo",
    "moll", "moly", "momo", "mona", "mong", "mont", "moor", "mora",
    "morg", "moro", "mort", "mose", "mott", "moya", "muir", "musa",
    "myra", "nada", "naga", "naik", "nair", "nana", "napa", "narc",
    "nasa", "nash", "nate", "nato", "neal", "neil", "nell", "nemo",
    "nein", "nene", "neri", "ngai", "nick", "nike", "nile", "nils", "nina",
    "ning", "noah", "noam", "noel", "noir", "noma", "nome", "nona",
    "nong", "nora", "nori", "nowt", "odin", "odum", "ohio", "okie", "olaf", "oleg",
    "olga", "olof", "oman", "omar", "omer", "oooo", "orly", "oslo", "otis", "otto",
    "ouzo", "owen", "paco", "pali", "pani", "pari", "parr", "paso", "paul", "pele", "pell",
    "peng", "pere", "peri", "perp", "peru", "peso", "pete", "petr",
    "phat", "phil", "pico", "pied", "piet", "pika", "pina", "pino",
    "pisa", "pish", "pius", "pixy", "poco", "pogo", "polk", "polo",
    "pong", "pont", "poon", "poof", "pows", "prat", "prem", "prig",
    "prix", "prob", "prue", "psst", "pugh", "puja", "puri", "pyro",
    "quai", "quan", "quot", "rach", "rada", "rafe", "raff", "raga", "raja",
    "raki", "ralf", "rama", "rami", "rana", "rane", "rani", "rasa",
    "rath", "raul", "ravi", "raya", "rebs", "rees", "reid", "reis",
    "remi", "reno", "renu", "reve", "rhea", "riga", "rita", "riva",
    "rolf", "rome", "rong", "roop", "rory", "rosa", "ross", "rota",
    "roti", "roux", "roxy", "rsvp", "rube", "ruby", "rudd", "rudy",
    "rukh", "rupa", "russ", "ruth", "saad", "saba", "sabe", "sade",
    "sado", "saki", "sala", "sant", "sara", "sari", "sark", "sasa",
    "saul", "saya", "scot", "sean", "secs", "sena", "serb", "seth",
    "seve", "shad", "shah", "shan", "shaw", "shay", "shea", "shel",
    "shen", "sher", "shia", "shih", "shik", "shiv", "shoo", "shou",
    "shri", "siam", "sikh", "sima", "sims", "sind", "sion", "sire",
    "sirs", "sisi", "sita", "sith", "situ", "siva", "skye", "slav",
    "smee", "soco", "soho", "soir", "soma", "sone", "sook", "soph",
    "sora", "sory", "sous", "stan", "sten", "styx", "suey", "suez",
    "sufi", "sugi", "sulu", "sumi", "sumo", "sune", "sura", "susi",
    "susu", "suzy", "syed", "syne", "tach", "taft", "taka", "taku",
    "tali", "tama", "tana", "tane", "tano", "tara", "tarr", "tash",
    "tate", "teat", "teng", "teri", "tess", "thad", "thai", "thar",
    "thea", "theo", "thor", "tien", "tiki", "timo", "tina", "tink",
    "tino", "titi", "tobe", "toby", "toda", "todd", "togo", "toho",
    "toke", "toma", "tony", "toph", "topo", "tora", "tori", "toro",
    "toru", "tory", "tosh", "toto", "tout", "toyo", "tran", "trav",
    "tres", "trey", "trix", "trog", "tron", "troy", "tsar", "tuan",
    "tula", "tung", "turk", "tush", "tutu", "twas", "tyne", "typo",
    "tyre", "ufos", "ulla", "urdu", "ursa", "ussr", "utah", "vail",
    "vali", "vasa", "vasu", "vayu", "veda", "vega", "vena", "vera",
    "vern", "vert", "vick", "viii", "vila", "vino", "vips", "vita",
    "vite", "viva", "vive", "wack", "waco", "wade", "wadi", "walt",
    "wang", "wasn", "wast", "watt", "wawa", "weet", "weir", "weve",
    "whee", "whoo", "whup", "wich", "wilk", "wino", "wong", "wont",
    "woon", "wort", "wray", "wren", "wuss", "wynn", "xiii", "xmas",
    "yale", "yana", "yang", "yank", "yeni", "ymca", "yogi", "yoni",
    "york", "youd", "yous", "yoyo", "yuki", "yule", "yuma",
    "zach", "zack", "zeke", "zeus", "zion", "zulu",

    # ── 5-letter names / places / acronyms ───────────────────
    "aaron", "abbas", "abbey", "abbie", "abbot", "abner", "abram",
    "acker", "actin", "adair", "adele", "admin", "adolf", "afoot",
    "agnes", "aidan", "aiken", "aimer", "aimee", "akbar", "alamo",
    "alana", "alban", "alder", "aldis", "alexa", "algae", "alice",
    "alida", "alina", "aline", "allan", "allen", "allie", "allot",
    "allyn", "altai", "alton", "alvin", "amara", "amato", "amber",
    "amend", "amiga", "amman", "ammon", "andes", "andre", "angel",
    "angie", "anglo", "anita", "anjou", "annan", "annie", "anton",
    "anzac", "aorta", "arabs", "arafat", "ariel", "arkin", "arlen",
    "arnie", "aruba", "aryan", "asher", "ashok", "asian", "aspen",
    "assam", "aston", "astra", "atlas", "attic", "auger", "aural",
    "auric", "avery", "avert", "avila", "avion", "ayres", "aztec",
    "babel", "bahia", "baker", "baldy", "baloo", "banff", "bangs",
    "banjo", "banks", "barak", "baron", "barry", "basho", "basil",
    "bates", "baton", "batty", "bawdy", "bayer", "bayou", "beads",
    "becky", "bedouin", "beebe", "beige", "being", "bella", "belle",
    "benny", "beryl", "betel", "betty", "bhatt", "bible", "biddy",
    "bidet", "billy", "biome", "blair", "blake", "blanc", "blase",
    "bliss", "blitz", "bloke", "bobby", "boise", "bolex", "boner",
    "bonny", "boone", "boots", "borat", "borax", "bored", "boris",
    "bossy", "bowen", "bowie", "boxer", "boyar", "brace", "brady",
    "brake", "brand", "brave", "bravo", "brawl", "bread", "break",
    "breed", "brent", "brett", "brian", "brick", "bride", "brief",
    "bring", "brink", "briny", "broad", "brody", "broke", "brook",
    "brown", "bruce", "brunt", "brush", "bryan", "buena", "bugle",
    "build", "built", "bunny", "buoys", "burke", "burly", "burns",
    "burst", "buyer", "byron", "cabal", "cabin", "cable", "cabot",
    "caddy", "cadet", "cairo", "cajun", "caleb", "camel", "cameo",
    "candy", "canoe", "canto", "capri", "cards", "carey", "cargo",
    "carlo", "carol", "casey", "caste", "cathy", "cause", "cecil",
    "cedar", "celia", "cello", "celtic", "cesar", "champ", "chaos",
    "chase", "cheap", "check", "cheek", "cheer", "chess", "chest",
    "chick", "chief", "child", "chile", "chili", "chill", "china",
    "chord", "chose", "chris", "chuck", "cindy", "circa", "cisco",
    "cited", "civil", "claim", "clara", "clark", "clash", "class",
    "clean", "clear", "clerk", "cliff", "climb", "cline", "cling",
    "clint", "clive", "clock", "clone", "close", "cloth", "cloud",
    "clown", "clyde", "coach", "coast", "cobra", "cohen", "comet",
    "comic", "comma", "conan", "congo", "coral", "corby", "corey",
    "costa", "could", "count", "coupe", "court", "cover", "covet",
    "crack", "craft", "craig", "crane", "crash", "crawl", "craze",
    "crazy", "cream", "creek", "creep", "crest", "crime", "crisp",
    "croat", "croix", "crook", "cross", "crowd", "crown", "crude",
    "cruel", "crush", "cuban", "cubic", "cupid", "curry", "cyrus",
    "czech", "daddy", "dainty", "dairy", "daisy", "damon", "dance",
    "dandy", "danny", "dante", "darcy", "darin", "david", "davis",
    "debug", "decal", "decor", "deity", "delay", "delhi", "della",
    "delta", "deluxe", "denim", "denny", "dense", "depot", "derby",
    "derek", "derry", "desks", "diana", "diane", "diego", "digit",
    "dimly", "dinar", "dingo", "dingy", "diode", "dirty", "disco",
    "dixie", "dizzy", "dodge", "dolly", "donna", "donor", "donut",
    "doria", "doris", "dover", "dowdy", "downs", "doyle", "draft",
    "drain", "drake", "drama", "drape", "dream", "dress", "dried",
    "drift", "drill", "drink", "drive", "drone", "drool", "drove",
    "druid", "duchy", "dully", "dummy", "dumps", "dunce", "dusty",
    "dutch", "dwarf", "dwell", "dylan", "eagle", "earth", "eater",
    "ebony", "edgar", "eddie", "edith", "egret", "egypt", "eject",
    "elbow", "elder", "elena", "eliot", "elite", "ellen", "ellis",
    "elmer", "elton", "elvis", "ember", "emile", "emily", "emmet",
    "emory", "enact", "ended", "ennui", "enoch", "enter", "entry",
    "envoy", "epoch", "epoxy", "equal", "equip", "erica", "ernie",
    "ernst", "error", "essex", "essie", "ester", "ethel", "ether",
    "ethic", "ethos", "euler", "euros", "event", "every", "evict",
    "exact", "exalt", "exams", "excel", "exert", "exile", "exist",
    "expat", "extra", "exude", "eying", "fable", "facet", "facto",
    "fagot", "faith", "famed", "fancy", "farce", "fauna", "feast",
    "ferry", "fever", "fibre", "field", "fifth", "fifty", "fight",
    "filth", "final", "finch", "fiona", "first", "fjord", "flame",
    "flank", "flare", "flash", "flask", "fleet", "fling", "flint",
    "flirt", "float", "flock", "flood", "floor", "flora", "floss",
    "flour", "fluid", "fluke", "flung", "flush", "flute", "focal",
    "focus", "foggy", "folio", "folly", "foray", "force", "forge",
    "forte", "forth", "forum", "found", "foyer", "frail", "frame",
    "franc", "frank", "fraud", "freed", "fresh", "freud", "friar",
    "fritz", "front", "frost", "froze", "fruit", "fudge", "fugue",
    "fully", "fungi", "funny", "fuzzy", "gabon", "gaily", "galen",
    "gamma", "gangs", "garry", "gavin", "genre", "gerry", "ghana",
    "giant", "giddy", "girls", "given", "gland", "glare", "glass",
    "glaze", "gleam", "glide", "glint", "globe", "gloom", "glory",
    "gloss", "glove", "gnome", "goats", "godly", "going", "gonzo",
    "goody", "goose", "gorge", "gotta", "gourd", "gowns", "grace",
    "grade", "grain", "grand", "grant", "grape", "graph", "grasp",
    "grass", "grate", "gravel", "gravy", "graze", "great", "greed",
    "greek", "green", "greet", "grief", "grill", "grind", "groan",
    "groom", "gross", "group", "grove", "growl", "grown", "guard",
    "guava", "guess", "guest", "guide", "guild", "guilt", "guise",
    "gupta", "guppy", "gypsy", "habit", "haiku", "haiti", "haley",
    "hands", "handy", "happy", "hardy", "harry", "harsh", "hasn't",
    "haste", "hasty", "haven", "hazel", "heads", "heart", "heavy",
    "hedge", "heidi", "helen", "helix", "hence", "henri", "henry",
    "herbs", "heron", "hilda", "hills", "hilly", "hindi", "hinge",
    "hippo", "hobby", "homer", "honda", "honey", "honor", "hoped",
    "horde", "horse", "hotel", "hound", "house", "hover", "human",
    "humid", "humor", "hurry", "hyena", "hymns", "hyper", "idaho",
    "ideal", "image", "incur", "index", "india", "indie", "inept",
    "infer", "ingot", "inner", "input", "intel", "inter", "intro",
    "ionic", "irene", "irish", "irony", "isaac", "isham", "islam",
    "ivory", "jacob", "james", "jamie", "janet", "japan", "jason",
    "jazzy", "jelly", "jenny", "jerez", "jerry", "jesse", "jimmy",
    "jodie", "joint", "joker", "jolly", "jorge", "josie", "joust",
    "joyce", "judge", "juice", "juicy", "jules", "julia", "julie",
    "jumbo", "jumpy", "kabul", "kafka", "karen", "karma", "kathy",
    "katie", "kazoo", "keats", "kebab", "keith", "kelli", "kelly",
    "kenny", "kenya", "kevin", "khaki", "knack", "knead", "kneel",
    "knife", "knock", "known", "kodak", "koran", "kraft", "kraut",
    "krebs", "krupp", "kudos", "label", "labor", "laden", "ladle",
    "lance", "largo", "larry", "laser", "latch", "later", "latex",
    "latin", "laugh", "laura", "layer", "leads", "leafy", "learn",
    "lease", "least", "leave", "ledge", "legal", "leigh", "lemon",
    "leone", "leroy", "level", "lever", "lewis", "libby", "libya",
    "light", "limbo", "limit", "linen", "liner", "lingo", "links",
    "linux", "llama", "llano", "lloyd", "lobby", "local", "lodge",
    "lofty", "logan", "logic", "looks", "loose", "lopez", "lorry",
    "lotus", "louie", "louis", "lover", "lower", "loyal", "lucia",
    "lucky", "luigi", "luisa", "lurch", "lydia", "lynch", "lyric",
    "mabel", "macho", "macro", "madam", "madly", "mafia", "magic",
    "magma", "magna", "major", "maker", "malik", "malta", "mamma",
    "mammy", "mandy", "manga", "mange", "mango", "mania", "manor",
    "maple", "marat", "march", "marco", "marge", "maria", "marie",
    "mario", "mason", "mater", "matey", "maude", "mavis", "maxim",
    "mayor", "meade", "meant", "medal", "media", "medic", "melee",
    "melon", "mercy", "merge", "merit", "merle", "merry", "messi",
    "metal", "meter", "metro", "meyer", "micro", "midst", "might",
    "mikey", "milan", "milky", "mills", "mimic", "mince", "miner",
    "minor", "minus", "mirth", "miser", "missy", "mists", "misty",
    "mitch", "mitre", "mixed", "mixer", "modal", "model", "modem",
    "mogul", "molly", "money", "monte", "month", "moody", "moose",
    "moral", "morel", "moses", "mossy", "motel", "motet", "motor",
    "motto", "mould", "mound", "mount", "mourn", "mouse", "mouth",
    "movie", "mucus", "muddy", "mural", "murky", "mushy", "music",
    "musty", "nancy", "naomi", "narco", "natal", "naval", "navel",
    "needy", "negro", "nepal", "nerve", "never", "newly", "nexus",
    "niche", "nicky", "niger", "nigel", "night", "ninny", "ninth",
    "noble", "nolan", "norma", "norse", "north", "notch", "noted",
    "novel", "nudge", "nurse", "nylon", "oasis", "occur", "ocean",
    "olive", "ollie", "omega", "onset", "opera", "optic", "orbit",
    "order", "organ", "oscar", "other", "otter", "ought", "ounce",
    "outer", "outdo", "outwit", "ovary", "owing", "oxide", "ozone",
    "pablo", "paddy", "padre", "pagan", "panda", "panel", "papua",
    "papal", "paris", "patch", "patio", "patsy", "patti", "patty",
    "paula", "pauli", "pause", "pearl", "pecan", "pedal", "pedro",
    "penal", "pence", "penny", "peppy", "perch", "peril", "perky",
    "perry", "pesky", "petal", "peter", "petra", "petty", "phase",
    "photo", "piano", "piece", "pilot", "pinch", "pixel", "pixie",
    "pizza", "place", "plaid", "plain", "plane", "plank", "plant",
    "plate", "plaza", "plead", "pleat", "plied", "pluck", "plumb",
    "plume", "plump", "pluck", "plumb", "plume", "plump", "plunge",
    "plush", "poach", "poems", "point", "polar", "polka", "polyp",
    "pooch", "posse", "potty", "pouch", "pound", "power", "prank",
    "press", "price", "pride", "prime", "print", "prior", "prism",
    "privy", "prize", "probe", "prone", "proof", "prose", "proud",
    "prove", "prude", "prune", "psalm", "pubic", "pulse", "punky",
    "pupil", "puppy", "purge", "purse", "pushy", "quail", "quake",
    "qualm", "queen", "query", "quest", "queue", "quick", "quiet",
    "quill", "quilt", "quirk", "quota", "quote", "rabbi", "rabid",
    "radar", "radio", "radon", "rahul", "rajah", "rajiv", "rally",
    "ralph", "ramen", "ramos", "ranch", "randy", "range", "ranks",
    "rapid", "ratio", "raven", "rayon", "reach", "realm", "rebel",
    "recap", "recon", "recur", "reese", "regal", "reign", "relax",
    "relay", "remit", "renee", "repay", "repel", "reply", "rerun",
    "reset", "resin", "retro", "rhino", "rhyme", "rider", "ridge",
    "rigid", "riley", "rinse", "ripen", "risen", "risky", "rivet",
    "rival", "river", "roast", "robin", "robot", "rocky", "rodeo",
    "roger", "rogue", "roman", "romeo", "roost", "round", "route",
    "rover", "rowdy", "royal", "rufus", "rugby", "ruler", "rumba",
    "rumor", "rural", "russo", "rusty", "sadie", "sadly", "saint",
    "sally", "salon", "samoa", "sandy", "sango", "santa", "sarah",
    "satin", "satire", "sauce", "saudi", "sauna", "savor", "scale",
    "scald", "scalp", "scene", "scent", "scone", "scoop", "scope",
    "score", "scout", "scrap", "scrub", "sedan", "seize", "sense",
    "sepia", "setup", "seven", "sever", "shade", "shaft", "shake",
    "shall", "shame", "shape", "share", "shark", "sharp", "shave",
    "shawl", "shawm", "sheen", "sheep", "sheer", "sheet", "shelf",
    "shell", "shift", "shine", "shiny", "shire", "shirt", "shock",
    "shore", "short", "shout", "shove", "shown", "showy", "shrub",
    "shrug", "siege", "sighs", "sight", "sigma", "silky", "silly",
    "simon", "since", "sinew", "siren", "sissy", "sixth", "sixty",
    "sized", "skate", "sketchy", "skill", "skimp", "skirt", "skull",
    "slack", "slang", "slash", "slate", "slave", "sleek", "sleep",
    "slept", "slice", "slide", "slope", "sloth", "small", "smart",
    "smell", "smile", "smith", "smoky", "snack", "snail", "snake",
    "snare", "sneak", "sniff", "sonar", "sonic", "sorry", "sound",
    "south", "space", "spade", "spain", "spare", "spark", "speak",
    "spear", "speed", "spell", "spend", "spent", "spice", "spicy",
    "spill", "spine", "spoke", "spoon", "sport", "spray", "spree",
    "sprig", "squab", "squad", "squat", "squid", "stack", "staff",
    "stage", "staid", "stain", "stair", "stake", "stale", "stall",
    "stamp", "stand", "stank", "stare", "stark", "start", "stash",
    "state", "stave", "stead", "steak", "steam", "steel", "steep",
    "steer", "steve", "stick", "stiff", "still", "sting", "stint",
    "stock", "stoic", "stole", "stomp", "stone", "stood", "stool",
    "stoop", "store", "stork", "storm", "story", "stout", "stove",
    "strap", "straw", "stray", "strip", "strum", "strut", "stuck",
    "study", "stuff", "stump", "stung", "stunk", "style", "suave",
    "sudan", "sugar", "suite", "sunny", "super", "surge", "susan",
    "susie", "swamp", "swarm", "swear", "sweat", "sweep", "sweet",
    "swept", "swift", "swine", "swing", "swipe", "swirl", "swore",
    "sworn", "swung", "sybil", "syria", "syrup", "tacit", "taffy",
    "taint", "taken", "tales", "tamil", "tango", "tapir", "tardy",
    "taste", "tasty", "taunt", "taxes", "teach", "tears", "tease",
    "teddy", "teeth", "tempo", "tense", "tepid", "terms", "terry",
    "texas", "thick", "thigh", "thing", "think", "third", "thorn",
    "those", "three", "threw", "throw", "thumb", "thump", "tiara",
    "tidal", "tiger", "tight", "tiles", "times", "timid", "tipsy",
    "tired", "titan", "title", "titus", "toast", "today", "token",
    "tommy", "tonal", "tonga", "tonic", "tools", "topic", "topaz",
    "total", "touch", "tough", "towel", "tower", "towns", "trace",
    "track", "trade", "trail", "train", "trait", "trash", "tread",
    "treat", "trend", "trial", "tribe", "trick", "tried", "troop",
    "trout", "truce", "truck", "truly", "trump", "trunk", "trust",
    "truth", "tudor", "tulip", "tumor", "tuner", "tunic", "tutor",
    "tweed", "twice", "twist", "tyler", "ulcer", "ultra", "umbra",
    "uncle", "uncut", "under", "undue", "unfed", "unfit", "unify",
    "union", "unite", "unity", "unlit", "unmet", "unpin", "untie",
    "until", "unwed", "upper", "upset", "urban", "usher", "usual",
    "utter", "uzbek", "vague", "valid", "valor", "valve", "vapor",
    "vault", "venus", "verge", "verse", "vexed", "vicar", "video",
    "vigil", "vigor", "vince", "vinyl", "viola", "viper", "viral",
    "virus", "visor", "visit", "vista", "vital", "vivid", "vocal",
    "vodka", "vogue", "voice", "voter", "vouch", "vowel", "vulva",
    "wafer", "wagon", "waist", "wally", "waltz", "wanda", "watch",
    "water", "wayne", "weary", "weave", "wedge", "weedy", "weigh",
    "weird", "wells", "wendy", "whale", "wheat", "wheel", "where",
    "which", "while", "whine", "whirl", "white", "whole", "whose",
    "widen", "wider", "widow", "width", "wield", "willy", "windy",
    "wired", "witch", "woman", "women", "world", "worry", "worse",
    "worst", "worth", "would", "wrack", "wrath", "wreak", "write",
    "wrong", "wrote", "xenon", "yacht", "yearn", "yeast", "yield",
    "young", "yours", "youth", "zebra", "zippy", "zonal",

    # ── 6-letter names / places / acronyms ───────────────────
    "adidas", "adrian", "africa", "agatha", "aiesha", "aikido",
    "alaska", "albert", "aldrin", "alexei", "alexis", "alfred",
    "alicia", "allahu", "amanda", "amazon", "amelia", "andrea",
    "andrew", "angelo", "angola", "anyhow", "apache", "apollo",
    "arctic", "ariana", "arnold", "arthur", "arushi", "ashton",
    "austin", "balkan", "baltic", "bamako", "barbie", "barney",
    "baruch", "basque", "bengal", "berger", "berlin", "bernie",
    "bhutan", "bianca", "bisque", "blonde", "bonnie", "boston",
    "brahms", "brenda", "brigid", "brooke", "brutus", "buddha",
    "buenos", "calvin", "canada", "cannes", "carbon", "carlos",
    "carmen", "carrie", "carter", "castro", "celtic", "cherub",
    "cheryl", "christ", "chrome", "claire", "claude", "cleric",
    "cobalt", "collin", "connor", "conrad", "conway", "cooper",
    "corina", "curios", "dallas", "damian", "daniel", "danube",
    "daphne", "darwin", "debbie", "dennis", "denver", "dexter",
    "diesel", "dmitri", "donald", "dorsey", "dublin", "duncan",
    "dunlop", "dustin", "dwight", "easter", "easton", "edmond",
    "edmund", "edward", "elaine", "elvira", "emilia", "emmett",
    "ernest", "esther", "eugene", "europa", "europe", "evelyn",
    "exeter", "fabian", "farley", "fatima", "fergus", "ferris",
    "france", "gandhi", "gareth", "gaelic", "gemini", "geneva",
    "george", "gerald", "german", "gibson", "gideon", "ginger",
    "girard", "gladys", "glenda", "gloria", "godiva", "gordon",
    "gothic", "gracia", "gracie", "granny", "greece", "grover",
    "gustav", "hailey", "hamlet", "hannah", "harold", "harris",
    "harvey", "hassan", "hawaii", "hayden", "hebrew", "hector",
    "helena", "henley", "herman", "hermes", "hilary", "hilton",
    "holden", "hoover", "howard", "hudson", "humpty", "hunter",
    "hustle", "ingrid", "irvine", "irving", "isabel", "israel",
    "jackal", "jackie", "jaguar", "janice", "jarvis", "jasper",
    "jeeves", "jerome", "jersey", "jesuit", "jethro", "johnny",
    "jordan", "joseph", "joshua", "josiah", "judith", "julian",
    "julius", "junior", "justin", "kansas", "karate", "keller",
    "kelvin", "kendra", "kermit", "knight", "korean", "kosher",
    "kuwait", "lahore", "lauren", "lennon", "lester", "libyan",
    "lilian", "lisbon", "lizzie", "london", "lorena", "ludwig",
    "luther", "macbeth", "madrid", "maggie", "malawi", "manila",
    "marina", "marlon", "martha", "martin", "matron", "maxim",
    "mayor", "meade", "meant", "medal", "media", "medic", "melee",
    "melon", "mercy", "merge", "merit", "merle", "merry", "messi",
    "metal", "meter", "metro", "meyer", "micro", "midst", "might",
    "mikey", "milan", "milky", "mills", "mimic", "mince", "miner",
    "minor", "minus", "mirth", "miser", "missy", "mists", "misty",
    "mitch", "mitre", "mixed", "mixer", "modal", "model", "modem",
    "mogul", "molly", "money", "monte", "month", "moody", "moose",
    "moral", "morel", "moses", "mossy", "motel", "motet", "motor",
    "motto", "mould", "mound", "mount", "mourn", "mouse", "mouth",
    "movie", "mucus", "muddy", "mural", "murky", "mushy", "music",
    "musty", "nancy", "naomi", "narco", "natal", "naval", "navel",
    "needy", "negro", "nepal", "nerve", "never", "newly", "nexus",
    "niche", "nicky", "niger", "nigel", "night", "ninny", "ninth",
    "noble", "nolan", "norma", "norse", "north", "notch", "noted",
    "novel", "nudge", "nurse", "nylon", "oasis", "occur", "ocean",
    "olive", "ollie", "omega", "onset", "opera", "optic", "orbit",
    "order", "organ", "oscar", "other", "otter", "ought", "ounce",
    "outer", "outdo", "outwit", "ovary", "owing", "oxide", "ozone",
    "pablo", "paddy", "padre", "pagan", "panda", "panel", "papua",
    "papal", "paris", "patch", "patio", "patsy", "patti", "patty",
    "paula", "pauli", "pause", "pearl", "pecan", "pedal", "pedro",
    "penal", "pence", "penny", "peppy", "perch", "peril", "perky",
    "perry", "pesky", "petal", "peter", "petra", "petty", "phase",
    "photo", "piano", "piece", "pilot", "pinch", "pixel", "pixie",
    "pizza", "place", "plaid", "plain", "plane", "plank", "plant",
    "plate", "plaza", "plead", "pleat", "plied", "pluck", "plumb",
    "plume", "plump", "pluck", "plumb", "plume", "plump", "plunge",
    "plush", "poach", "poems", "point", "polar", "polka", "polyp",
    "pooch", "posse", "potty", "pouch", "pound", "power", "prank",
    "press", "price", "pride", "prime", "print", "prior", "prism",
    "privy", "prize", "probe", "prone", "proof", "prose", "proud",
    "prove", "prude", "prune", "psalm", "pubic", "pulse", "punky",
    "pupil", "puppy", "purge", "purse", "pushy", "quail", "quake",
    "qualm", "queen", "query", "quest", "queue", "quick", "quiet",
    "quill", "quilt", "quirk", "quota", "quote", "rabbi", "rabid",
    "radar", "radio", "radon", "rahul", "rajah", "rajiv", "rally",
    "ralph", "ramen", "ramos", "ranch", "randy", "range", "ranks",
    "rapid", "ratio", "raven", "rayon", "reach", "realm", "rebel",
    "recap", "recon", "recur", "reese", "regal", "reign", "relax",
    "relay", "remit", "renee", "repay", "repel", "reply", "rerun",
    "reset", "resin", "retro", "rhino", "rhyme", "rider", "ridge",
    "rigid", "riley", "rinse", "ripen", "risen", "risky", "rivet",
    "rival", "river", "roast", "robin", "robot", "rocky", "rodeo",
    "roger", "rogue", "roman", "romeo", "roost", "round", "route",
    "rover", "rowdy", "royal", "rufus", "rugby", "ruler", "rumba",
    "rumor", "rural", "russo", "rusty", "sadie", "sadly", "saint",
    "sally", "salon", "samoa", "sandy", "sango", "santa", "sarah",
    "satin", "satire", "sauce", "saudi", "sauna", "savor", "scale",
    "scald", "scalp", "scene", "scent", "scone", "scoop", "scope",
    "score", "scout", "scrap", "scrub", "sedan", "seize", "sense",
    "sepia", "setup", "seven", "sever", "shade", "shaft", "shake",
    "shall", "shame", "shape", "share", "shark", "sharp", "shave",
    "shawl", "shawm", "sheen", "sheep", "sheer", "sheet", "shelf",
    "shell", "shift", "shine", "shiny", "shire", "shirt", "shock",
    "shore", "short", "shout", "shove", "shown", "showy", "shrub",
    "shrug", "siege", "sighs", "sight", "sigma", "silky", "silly",
    "simon", "since", "sinew", "siren", "sissy", "sixth", "sixty",
    "sized", "skate", "sketchy", "skill", "skimp", "skirt", "skull",
    "slack", "slang", "slash", "slate", "slave", "sleek", "sleep",
    "slept", "slice", "slide", "slope", "sloth", "small", "smart",
    "smell", "smile", "smith", "smoky", "snack", "snail", "snake",
    "snare", "sneak", "sniff", "sonar", "sonic", "sorry", "sound",
    "south", "space", "spade", "spain", "spare", "spark", "speak",
    "spear", "speed", "spell", "spend", "spent", "spice", "spicy",
    "spill", "spine", "spoke", "spoon", "sport", "spray", "spree",
    "sprig", "squab", "squad", "squat", "squid", "stack", "staff",
    "stage", "staid", "stain", "stair", "stake", "stale", "stall",
    "stamp", "stand", "stank", "stare", "stark", "start", "stash",
    "state", "stave", "stead", "steak", "steam", "steel", "steep",
    "steer", "steve", "stick", "stiff", "still", "sting", "stint",
    "stock", "stoic", "stole", "stomp", "stone", "stood", "stool",
    "stoop", "store", "stork", "storm", "story", "stout", "stove",
    "strap", "straw", "stray", "strip", "strum", "strut", "stuck",
    "study", "stuff", "stump", "stung", "stunk", "style", "suave",
    "sudan", "sugar", "suite", "sunny", "super", "surge", "susan",
    "susie", "swamp", "swarm", "swear", "sweat", "sweep", "sweet",
    "swept", "swift", "swine", "swing", "swipe", "swirl", "swore",
    "sworn", "swung", "sybil", "syria", "syrup", "tacit", "taffy",
    "taint", "taken", "tales", "tamil", "tango", "tapir", "tardy",
    "taste", "tasty", "taunt", "taxes", "teach", "tears", "tease",
    "teddy", "teeth", "tempo", "tense", "tepid", "terms", "terry",
    "texas", "thick", "thigh", "thing", "think", "third", "thorn",
    "those", "three", "threw", "throw", "thumb", "thump", "tiara",
    "tidal", "tiger", "tight", "tiles", "times", "timid", "tipsy",
    "tired", "titan", "title", "titus", "toast", "today", "token",
    "tommy", "tonal", "tonga", "tonic", "tools", "topic", "topaz",
    "total", "touch", "tough", "towel", "tower", "towns", "trace",
    "track", "trade", "trail", "train", "trait", "trash", "tread",
    "treat", "trend", "trial", "tribe", "trick", "tried", "troop",
    "trout", "truce", "truck", "truly", "trump", "trunk", "trust",
    "truth", "tudor", "tulip", "tumor", "tuner", "tunic", "tutor",
    "tweed", "twice", "twist", "tyler", "ulcer", "ultra", "umbra",
    "uncle", "uncut", "under", "undue", "unfed", "unfit", "unify",
    "union", "unite", "unity", "unlit", "unmet", "unpin", "untie",
    "until", "unwed", "upper", "upset", "urban", "usher", "usual",
    "utter", "uzbek", "vague", "valid", "valor", "valve", "vapor",
    "vault", "venus", "verge", "verse", "vexed", "vicar", "video",
    "vigil", "vigor", "vince", "vinyl", "viola", "viper", "viral",
    "virus", "visor", "visit", "vista", "vital", "vivid", "vocal",
    "vodka", "vogue", "voice", "voter", "vouch", "vowel", "vulva",
    "wafer", "wagon", "waist", "wally", "waltz", "wanda", "watch",
    "water", "wayne", "weary", "weave", "wedge", "weedy", "weigh",
    "weird", "wells", "wendy", "whale", "wheat", "wheel", "where",
    "which", "while", "whine", "whirl", "white", "whole", "whose",
    "widen", "wider", "widow", "width", "wield", "willy", "windy",
    "wired", "witch", "woman", "women", "world", "worry", "worse",
    "worst", "worth", "would", "wrack", "wrath", "wreak", "write",
    "wrong", "wrote", "xenon", "yacht", "yearn", "yeast", "yield",
    "young", "yours", "youth", "zebra", "zippy", "zonal",

    # ── 7-letter names / places / acronyms ───────────────────
    "abilene", "abraham", "academy", "acrobat", "address", "admiral",
    "alabama", "albania", "alcatraz", "alchemy", "algebra", "algeria",
    "allegro", "almanac", "america", "analogy", "anatomy", "andorra",
    "annabel", "antigua", "antonio", "aphasia", "apostle", "aquatic",
    "arabian", "archaic", "armenia", "artemis", "article", "auction",
    "auditor", "austria", "average", "aviator", "babylon", "bahamas",
    "bahrain", "balance", "baldwin", "bandage", "baptism", "baptist",
    "barbary", "barbara", "baroque", "barrier", "basilic", "battery",
    "beastly", "beatles", "bedroom", "beijing", "belarus", "belfast",
    "belgian", "belgium", "bellboy", "benefit", "bermuda", "bicycle",
    "billion", "blanket", "blatant", "blazing", "bleaker", "blemish",
    "blessed", "blister", "bloated", "blotted", "bohemia", "bolivar",
    "bolivia", "bombard", "borough", "boulder", "bowling", "brandon",
    "breathe", "brewery", "bridget", "bristle", "britain", "british",
    "brittle", "bronson", "broaden", "buffalo", "bugatti", "builder",
    "bulldog", "bulwark", "bungler", "burnett", "burundi", "cabinet",
    "calcium", "caliber", "calorie", "cameron", "canteen", "capital",
    "captain", "captive", "capture", "caracas", "cardiac", "caribou",
    "carolyn", "cartoon", "cascade", "cashier", "catalog", "catered",
    "caution", "cavalry", "celsius", "central", "ceramic", "chaotic",
    "chapter", "charade", "charity", "charles", "charlie", "chariot",
    "charter", "checked", "chelsea", "chemist", "chester", "chicago",
    "chicken", "chimney", "chinese", "christi", "chronic", "circuit",
    "citizen", "classic", "claudia", "clement", "climate", "clinton",
    "closely", "closing", "cluster", "coastal", "coating", "cockpit",
    "coconut", "collage", "college", "colonel", "colored", "comfort",
    "command", "comment", "commons", "compact", "company", "compare",
    "compass", "compel", "compete", "complex", "compose", "compost",
    "compute", "comrade", "comoros", "conceal", "concede", "concept",
    "concern", "concert", "condemn", "conduct", "confess", "confide",
    "confine", "confirm", "conform", "confuse", "congest", "connect",
    "conquer", "consent", "consist", "consort", "consult", "contact",
    "contain", "contend", "content", "contest", "context", "control",
    "convene", "convert", "convict", "cooking", "copious", "cornell",
    "correct", "corrupt", "corsair", "costume", "cottage", "council",
    "counter", "country", "coupled", "courage", "courier", "courtesy",
    "covered", "craving", "creator", "cricket", "crimson", "cripple",
    "croatia", "crumble", "crusade", "crystal", "cuisine", "culture",
    "cumulus", "curacao", "curator", "current", "curtain", "cushion",
    "cypress", "czarina", "daniels", "deborah", "decimal", "decline",
    "default", "defence", "deficit", "delayed", "delilah", "deliver",
    "density", "denmark", "deposit", "dessert", "destiny", "details",
    "detroit", "develop", "devious", "devoted", "devotee", "diagram",
    "dialect", "diamond", "digital", "dilemma", "diploma", "disable",
    "discard", "discord", "disease", "disgust", "dismiss", "display",
    "dispose", "dispute", "distant", "distort", "disturb", "diverse",
    "divided", "divulge", "dolphin", "dominic", "donated", "donovan",
    "doorman", "doorway", "dorothy", "douglas", "dracula", "drastic",
    "drawing", "dreamer", "drifter", "drummer", "dubious", "duction",
    "dweller", "dynamic", "eastern", "eclipse", "economy", "ecstasy",
    "ecuador", "edition", "edifice", "educate", "effecte", "ejected",
    "elderly", "elected", "elegant", "element", "elliott", "ellison",
    "emerson", "emotion", "emperor", "empower", "enabled", "endemic",
    "endless", "endowed", "enforce", "engaged", "english", "enhance",
    "enlarge", "enraged", "ensured", "entered", "environ", "envious",
    "episode", "epitome", "equally", "erected", "eritrea", "erosion",
    "essence", "eternal", "ethical", "eugenia", "everest", "everett",
    "evident", "evolved", "examine", "example", "excerpt", "excited",
    "execute", "exhaust", "existed", "expense", "expired", "explain",
    "exploit", "explore", "exposed", "express", "extinct", "extract",
    "extreme", "eyebrow", "ezekiel", "faction", "factory", "faculty",
    "failing", "failure", "fairway", "falsely", "fantasy", "farming",
    "fashion", "fatigue", "feather", "feature", "federal", "fiction",
    "fifteen", "fighter", "finance", "finland", "fitting", "flannel",
    "flatter", "fleeing", "fleming", "flexion", "flicker", "florida",
    "flutter", "focused", "foothold", "foolish", "footage", "forbade",
    "foreign", "forever", "formula", "forsake", "fortune", "forward",
    "founded", "founder", "fragile", "frances", "francis", "frankie",
    "freddie", "freedom", "freeway", "freight", "frisbee", "fulfill",
    "further", "futures", "gabriel", "gainful", "galilee", "galileo",
    "gallant", "gallery", "garbage", "gardens", "garland", "garment",
    "garrett", "gauntly", "gazette", "genesis", "genetic", "genuine",
    "geology", "georgia", "gerhard", "germany", "gesture", "gilbert",
    "glamour", "glimpse", "glorify", "glowing", "goading", "goddard",
    "goodman", "gorilla", "gracious", "grahame", "grammar", "granted",
    "graphic", "gravity", "greenly", "gregory", "grenada", "greyish",
    "griffin", "grimace", "grizzly", "grounds", "growing", "gruffly",
    "guarani", "guarded", "guiding", "habitat", "hampton", "hancock",
    "handbag", "handily", "handful", "handler", "handout", "hanging",
    "hanover", "happily", "harbour", "hardest", "harmful", "harmony",
    "harness", "harvest", "hastily", "haughty", "heading", "healing",
    "healthy", "hearing", "hearken", "heating", "heather", "heavily",
    "helpful", "hemlock", "hepatic", "herding", "heretic", "heroine",
    "herself", "hidalgo", "hideous", "highway", "hilbert", "hillary",
    "himself", "history", "hitting", "hoffman", "holding", "holiday",
    "holland", "honesty", "hopeful", "horizon", "hostile", "housing",
    "houston", "howling", "humming", "humored", "hundred", "hunting",
    "hurried", "hussein", "hygiene", "iceland", "ideally", "illicit",
    "imagine", "immense", "imitate", "immoral", "implant", "implied",
    "implore", "imposed", "impress", "improve", "impulse", "inadept",
    "include", "incline", "imposed", "indexed", "indiana", "indoors",
    "induced", "inherit", "initial", "innings", "inquire", "inquiry",
    "inspect", "inspire", "install", "instant", "instead", "insulin",
    "interim", "intrude", "invalid", "invaded", "invoice", "involve",
    "ireland", "islamic", "isolate", "israeli", "jackson", "jalouse",
    "jamaica", "jamming", "january", "jasmine", "javelin", "jeannie",
    "jenkins", "jessica", "jewelry", "jocelyn", "johnson", "jointly",
    "journal", "journey", "jubilee", "judaism", "judging", "juggler",
    "jupiter", "justice", "justify", "kathryn", "keeping", "kennedy",
    "kenneth", "killjoy", "kindred", "kingdom", "kitchen", "klondike",
    "knitted", "knocked", "kunming", "lacking", "ladybug", "lambent",
    "lambert", "landing", "laotian", "largely", "lasting", "latency",
    "lateral", "lathery", "laughed", "laundry", "lawsuit", "leading",
    "learner", "leather", "leaving", "lebanon", "lecture", "legally",
    "leisure", "lending", "lengthy", "leonard", "leopold", "lesbian",
    "letters", "lettuce", "liberty", "liberia", "library", "licence",
    "lighten", "lighter", "lightly", "lighter", "limited", "lincoln",
    "lindsey", "linking", "lioness", "literal", "lithium", "liturgy",
    "locally", "located", "logical", "lombard", "lengthy", "lookout",
    "lorenzo", "lottery", "loudest", "luggage", "lullaby", "lumpish",
    "lunatic", "lyrical", "macabre", "machine", "madison", "madonna",
    "magenta", "magical", "magnify", "mahogany", "mahoney", "mailbox",
    "mailman", "majesty", "makings", "malaria", "malcolm", "mammoth",
    "managed", "manager", "mandala", "mandela", "mandate", "mankind",
    "manning", "mansion", "mapping", "marched", "marital", "marking",
    "marlowe", "married", "martial", "martian", "marvelous", "massage",
    "massive", "mastery", "matched", "mathews", "matthew", "matinee",
    "matters", "matured", "maureen", "maximal", "meaning", "measure",
    "medical", "meeting", "melissa", "melodic", "melting", "memphis",
    "memento", "memoir", "mercury", "michael", "midland", "midterm",
    "midwest", "migrant", "militia", "million", "mineral", "minimal",
    "minimum", "miracle", "missile", "missing", "mission", "mistake",
    "mixture", "modular", "moliere", "monitor", "montana", "monthly",
    "morally", "morning", "mounted", "mourned", "movable", "mueller",
    "mulberry", "mundane", "murmuring", "musical", "mustard", "mystery",
    "myanmar", "namibia", "narrate", "natalie", "natural", "naughty",
    "nearest", "nebular", "necklace", "needful", "neglect", "neither",
    "neptune", "nervous", "nestled", "network", "neutral", "neumann",
    "niagara", "nickelodeon", "nigeria", "nipples", "nominal", "norfolk",
    "notable", "nothing", "noticed", "novelty", "nowhere", "nuclear",
    "numeric", "nursery", "nutrient", "oakland", "oatmeal", "obscure",
    "observe", "obvious", "october", "offense", "offered", "officer",
    "offline", "olympic", "olympia", "ongoing", "opening", "operate",
    "opinion", "optical", "optimal", "organic", "orlando", "orpheus",
    "outline", "outlook", "outrage", "outside", "overall", "overlap",
    "oversee", "pacific", "package", "padding", "paisley", "palermo",
    "palette", "parking", "partial", "partner", "passage", "passing",
    "passion", "passive", "pathway", "patient", "patrick", "patriot",
    "pattern", "pauline", "payment", "pearson", "peasant", "peddler",
    "penalty", "pending", "pension", "percent", "perfect", "perform",
    "perhaps", "persian", "persist", "phoenix", "pianist", "picasso",
    "pickles", "picnics", "picture", "pierced", "pilgrim", "pioneer",
    "planked", "planned", "planner", "plastic", "plateau", "playful",
    "pleased", "plenary", "pledged", "plotter", "plunder", "pointed",
    "polaris", "polices", "politic", "pontiac", "popular", "porsche",
    "portion", "portray", "posting", "postage", "posture", "potomac",
    "pottery", "poverty", "powered", "prairie", "precede", "precise",
    "predict", "preface", "premier", "premium", "prepare", "present",
    "preside", "pressed", "presume", "pretend", "prevail", "prevent",
    "preview", "primate", "primary", "printed", "printer", "privacy",
    "private", "problem", "proceed", "process", "proctor", "produce",
    "product", "profile", "profuse", "program", "project", "prolate",
    "promise", "promote", "pronoun", "prophet", "propose", "prosper",
    "protect", "protein", "protest", "proudly", "proverbial", "provide",
    "provoke", "prowler", "prudent", "publish", "puritan", "pursuit",
    "puzzled", "pyramid", "qualify", "quality", "quantum", "quarrel",
    "quarter", "quentin", "quickly", "quietly", "quilted", "radical",
    "ragtime", "railway", "rainbow", "ramirez", "rampant", "rancher",
    "ranging", "ranking", "rapidly", "rapport", "raphael", "raymond",
    "readied", "readily", "reading", "realist", "reality", "realize",
    "realtor", "rebuilt", "rebecca", "receipt", "receive", "recital",
    "reclaim", "recluse", "recover", "recruit", "rectify", "reduced",
    "referee", "refined", "reflect", "refused", "refugee", "regatta",
    "regimen", "regress", "regular", "related", "relaxed", "release",
    "reliant", "remains", "remedic", "remnant", "removal", "renewed",
    "repairs", "replete", "replica", "request", "require", "rescued",
    "reserve", "reshape", "resided", "residue", "resolve", "respect",
    "respond", "restore", "retired", "retreat", "reunion", "revenge",
    "revenue", "reverse", "revised", "revival", "revolve", "rhyming",
    "ricardo", "richard", "richest", "roberto", "roberts", "rodgers",
    "rodrigo", "rogue", "rolland", "rolling", "romance", "romulus",
    "routine", "roxanne", "rudolph", "ruffled", "rumpled", "running",
    "rupture", "russell", "russian", "sacrament", "salvage", "samurai",
    "sanctum", "sandbox", "satiric", "satisfy", "scatter", "scenery",
    "scholar", "science", "scratch", "sculpted", "section", "secured",
    "seeking", "seeming", "seizure", "selects", "selling", "seminar",
    "senator", "sensible", "sending", "serious", "serpent", "servant",
    "service", "session", "setting", "settled", "settler", "seventh",
    "several", "shallow", "shannon", "sharply", "shatter", "shelter",
    "sheldon", "shelley", "shepard", "sheriff", "shields", "shifted",
    "shipped", "shocked", "shortly", "shouted", "shoving", "showing",
    "showman", "shutout", "shuttle", "sibling", "sigmoid", "silence",
    "silicon", "similar", "simmons", "simpson", "sincere", "singing",
    "sitting", "sixteen", "skeptic", "skilled", "slammed", "slavery",
    "slender", "slipped", "slogan", "smaller", "smoking", "smother",
    "snippet", "society", "softens", "softest", "soldier", "solomon",
    "solving", "somehow", "sorting", "souffle", "sparked", "spanish",
    "spartan", "spatial", "speaker", "special", "species", "specify",
    "spencer", "spender", "spheres", "spinach", "spindle", "spinner",
    "spirits", "sponsor", "spotted", "spotter", "squeeze", "stagger",
    "staging", "stamina", "stanley", "startle", "station", "statues",
    "statute", "staying", "stealth", "steamer", "steward", "stewart",
    "sticker", "stiffen", "stilton", "stoical", "storage", "stories",
    "strange", "stretch", "strings", "striped", "student", "studied",
    "stumble", "subject", "subdued", "submits", "subsidy", "subplot",
    "suburbs", "succeed", "success", "succumb", "sudenly", "suggest",
    "suicide", "sulphur", "sumatra", "summary", "summers", "summons",
    "sunrise", "support", "supreme", "surface", "surgeon", "surname",
    "surplus", "surpass", "surplus", "surreal", "survive", "suspect",
    "suspend", "sustain", "swahili", "swagger", "sweater", "swedish",
    "tabletop", "tactics", "terrain", "textile", "theater", "theorem",
    "therapy", "theresa", "thereby", "thermal", "thicket", "thinker",
    "thirsty", "thought", "threads", "through", "thunder", "ticking",
    "timothy", "tobacco", "toilets", "tolkien", "tonight", "topmost",
    "toronto", "touched", "tourism", "tourist", "tractor", "trading",
    "traffic", "trained", "trainer", "transit", "travels", "treated",
    "trebled", "tribune", "tribute", "trigger", "trilogy", "trinity",
    "tristan", "triumph", "trivial", "trolley", "trouble", "trucker",
    "trumpet", "trusted", "trustee", "tsunami", "tuesday", "tunisia",
    "turbine", "turkish", "turning", "twisted", "typical", "ukraine",
    "undying", "uniform", "unknown", "unlocks", "unusual", "updated",
    "upgrade", "upright", "uranium", "urgency", "uruguay", "usually",
    "utility", "utopian", "utterly", "vacancy", "vaccine", "valerie",
    "vampire", "vanilla", "variety", "various", "varying", "vatican",
    "vehicle", "venture", "verdict", "vermont", "version", "veteran",
    "vibrant", "viceroy", "victims", "vietnam", "villain", "vincent",
    "vintage", "violate", "violent", "virtual", "visible", "visitor",
    "vitamin", "vivaldi", "volcano", "voltage", "volumes", "waiting",
    "walking", "wallace", "wanting", "warfare", "warming", "warning",
    "warrant", "warship", "wartime", "warwick", "washing", "wasting",
    "watched", "weather", "website", "wedding", "weekday", "weekend",
    "welcome", "welfare", "western", "whisper", "whitman", "whitney",
    "whoever", "wielded", "wilhelm", "william", "willing", "winning",
    "winston", "wishing", "witness", "woodcut", "wordily", "working",
    "workout", "worship", "writing", "written", "wrongly", "yiddish",
    "younger", "zealand",
}


def download_words():
    """Download the full word list."""
    print("Downloading word list from dwyl/english-words ...")
    response = urllib.request.urlopen(DWYL_URL)
    text = response.read().decode("utf-8")
    words = text.strip().splitlines()
    print(f"  Downloaded {len(words)} raw words")
    return words


def download_frequency():
    """Download word frequency data. Returns a set of common words."""
    print("Downloading word frequency data ...")
    response = urllib.request.urlopen(FREQ_URL)
    text = response.read().decode("utf-8")
    freq_words = set()
    for line in text.strip().splitlines():
        parts = line.split()
        if parts:
            word = parts[0].strip().lower()
            if re.match(r'^[a-z]+$', word):
                freq_words.add(word)
    print(f"  Downloaded {len(freq_words)} frequency entries")
    return freq_words


def is_likely_proper_noun(word):
    """
    Heuristic check: does the word look like a proper noun / name / acronym?
    The frequency data from Wikipedia includes names like 'john', 'paris', etc.
    because they appear in article text. We filter these out.
    """
    w = word.lower()

    # Check blocklist and names list
    if w in BLOCKLIST or w in NAMES_AND_ACRONYMS:
        return True

    return False


def filter_words(raw_words, freq_words, length):
    """
    Filter words: must be in both the dictionary AND the frequency list,
    correct length, alpha-only, not in blocklist, not a name/acronym.
    """
    result = set()
    for w in raw_words:
        w = w.strip().lower()
        if len(w) != length:
            continue
        if not re.match(r'^[a-z]+$', w):
            continue
        if is_likely_proper_noun(w):
            continue
        # Only keep words that appear in frequency data (common words)
        if w in freq_words:
            result.add(w.upper())
    return sorted(result)


def main():
    os.makedirs(ASSETS_DIR, exist_ok=True)
    raw_words = download_words()
    freq_words = download_frequency()

    total = 0
    for length in range(4, 8):
        words = filter_words(raw_words, freq_words, length)
        output_path = os.path.join(ASSETS_DIR, f"words_{length}.txt")
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(words) + "\n")
        print(f"  words_{length}.txt: {len(words)} words written")
        total += len(words)

    print(f"\nTotal: {total} words across all lists")
    print("Done! Word lists saved to app/src/main/assets/")


if __name__ == "__main__":
    main()

